### ISSUE TITLE
mem issues

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#629]
```
../../src/include/Rinlinedfuns.h:525:13: runtime error: member access within null pointer of type 'struct SEXPREC'
    #0 0x7fef84d7215d in Rf_length /tmp/r-source/src/main/../../src/include/Rinlinedfuns.h:525:13
    nlmixr2/rxode2parse#1 0x7fef6916bdc7 in _rxode2parse_udfEnvSet /home/matt/src/rxode2/src/rxode2parse.cpp:108:16
```

**Comment by mattfidler** [comment]
```sh
rxData.cpp:4889:5: runtime error: call to function _rxode2random_seedEng through pointer to incorrect function type 'void (*)(unsigned int)'
/tmp/RtmpNT2FvY/R.INSTALL2165bf0d102/rxode2random/src/rxthreefry.cpp:829: note: _rxode2random_seedEng defined here
    #0 0x7fe6905265b3 in rxSolve_(Rcpp::RObject_Impl<Rcpp::PreserveStorage> const&, Rcpp::Vector<19, Rcpp::PreserveStorage> const&, Rcpp::Nullable<Rcpp::Vector<16, Rcpp::PreserveStorage>> const&, Rcpp::Nullable<Rcpp::Vector<19, Rcpp::PreserveStorage>> const&, Rcpp::RObject_Impl<Rcpp::PreserveStorage> const&, Rcpp::RObject_Impl<Rcpp::PreserveStorage> const&, Rcpp::RObject_Impl<Rcpp::PreserveStorage> const&, int) /home/matt/src/rxode2/src/rxData.cpp:4889:5
    #1 0x7fe69058e18d in rxSolveSEXP(SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*) /home/matt/src/rxode2/src/rxData.cpp:6033:10
```

**Comment by mattfidler** [comment]
```sh
rxode-issue-468                                                                        using C compiler: ‘Ubuntu clang version 15.0.7’

=================================================================
==3468==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60b00002e310 at pc 0x7f906c2e68cb bp 0x7ffff4a31cc0 sp 0x7ffff4a31cb8
READ of size 4 at 0x60b00002e310 thread T0
    #0 0x7f906c2e68ca in getValue /home/matt/src/rxode2/src/approx.c:85:22
    #1 0x7f906c2ef3ad in _update_par_ptr /home/matt/src/rxode2/src/approx.c:298:32
```
